const fakeSwiggyData = [
  // Data for seven restaurants
  {
    id: "rest001",
    name: "The Spicy Spoon",
    address: "123 Food Street",
    city: "Metropolis",
    latitude: 12.9716,
    longitude: 77.5946,
    cuisine: "Indian",
    ratings: 4.5,
  },
  {
    id: "rest002",
    name: "Sushi Haven",
    address: "456 Ocean Avenue",
    city: "Coastal City",
    latitude: 34.0522,
    longitude: -118.2437,
    cuisine: "Japanese",
    ratings: 4.7,
  },
  {
    id: "rest003",
    name: "The Pasta Place",
    address: "789 Noodle Lane",
    city: "Gourmet Town",
    latitude: 51.5099,
    longitude: -0.118,
    cuisine: "Italian",
    ratings: 4.6,
  },
  {
    id: "rest004",
    name: "Grill & Chill",
    address: "321 Barbecue Blvd",
    city: "Smoke City",
    latitude: 40.7128,
    longitude: -74.006,
    cuisine: "Barbecue",
    ratings: 4.4,
  },
  {
    id: "rest005",
    name: "Taco Fiesta",
    address: "654 Sombrero Street",
    city: "Fiesta Town",
    latitude: 29.7604,
    longitude: -95.3698,
    cuisine: "Mexican",
    ratings: 4.3,
  },
  {
    id: "rest006",
    name: "Curry Junction",
    address: "987 Spice Road",
    city: "Flavor City",
    latitude: 28.6139,
    longitude: 77.209,
    cuisine: "Indian",
    ratings: 4.5,
  },
  {
    id: "rest007",
    name: "Vegan Delights",
    address: "321 Green Leaf Street",
    city: "Healthville",
    latitude: 34.0522,
    longitude: -118.2437,
    cuisine: "Vegan",
    ratings: 4.6,
  },
];

export default fakeSwiggyData;
